name: Vale Lint (Changed Markdown Only)

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  vale:
    name: Vale style check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post PR comments
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Vale
        run: |
          pip install vale

      - name: Get changed Markdown files
        id: changed
        run: |
            git fetch origin ${{ github.base_ref }}
            git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.md' > changed_files.txt
            echo "Changed files:"
            cat changed_files.txt
        
      - name: Run Vale on changed Markdown files
        run: |
            if [ -s changed_files.txt ]; then
              echo "Running Vale on:"
              cat changed_files.txt
        
              # Run Vale on each file individually (safer than passing all at once)
              fail=0
              while read -r file; do
                echo "::group::Vale output for $file"
                vale --config=.vale/.vale.ini "$file" || fail=1
                echo "::endgroup::"
              done < changed_files.txt
        
              if [ "$fail" -ne 0 ]; then
                echo "❌ Vale style issues found."
                exit 1
              else
                echo "✅ No Vale issues found."
              fi
            else
              echo "No changed Markdown files found."
            fi
        
        